### ISSUE TITLE
Shows previous trains

### ISSUE THREAD

**Issue by jeremyfritzen** [lgmorand/MMM-Transilien#7]
I've been using this module for a long time. Thank you so much for your work!

For a while, I see that the module shows the 2 previous trains, instead of showing next trains.
I already tried to update the MagicMirror and the module itself (by `git pull && npm install` command).

For example, it's now 13:31. Below is what I see on my Mirror:
![image](https://user-images.githubusercontent.com/26802442/64693821-771cbb80-d498-11e9-838c-d56e737e3a58.png)

Did anyone already experienced this issue?

Thanks for your help!

**Comment by lgmorand** [comment]
"
Nous vous remercions d’avoir fait remonter ce dysfonctionnement.
Effectivement la chaine d’alimentation de l’API a changé le 26/08, des correctifs sont en cours.

Veuillez nous excuser pour le désagrément, et n’hésitez pas à signaler si vous constatez d’autres soucis.

Cordialement,
"

bug on SNCF side, wrong time on server side. they are not really efficient to fix it...you have to wait for them to fix it, the issue is not on the plugin side ;-)
